/* Archive Index — reading rules for both archives.
   Generated by tools/extract.mjs; do not edit here. Rebuild when either archive's template changes. */
var AIX=window.AIX||(window.AIX={}); AIX.profiles={};
AIX.profiles.hl=(function(){
'use strict';
var D=null, TODAY=null, SINCE=null, saved={}, ALLNEW=false;
var F={y:{},cat:{},motif:{},price:{},src:{},cert:{},mark:{},flag:{},size:'',q:''};
/* ---- copied from helmut-lang template (r8b, as published 2026-09-28) ---- */
var won=function(n){return Number(n||0).toLocaleString('ko-KR')};
var SYM={USD:'$',GBP:'£',EUR:'€',JPY:'¥',KRW:'₩'};
var esc=function(s){return String(s==null?'':s).replace(/[&<>"]/g,function(c){
  return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})};
var MOTIF=[['bondage','본디지',/bondage|ボンデージ|ボンテージ|본디지|본테지/i],
 ['astro','애스트로',/astro|アストロ|아스트로|애스트로/i],['flak','M69 플락',/m69|flak|フラック|플락/i],
 ['bullet','방탄 베스트',/bullet ?proof|ballistic|防弾|バリスティック|방탄\s*(?:조끼|베스트|자켓|재킷|vest)|발리스틱/i],
 ['painter','페인터',/painter|ペインター|페인터/i],
 ['parachute','파라슈트',/parachute|パラシュート|파라슈트|낙하산/i],['taxi','택시',/taxi|タクシー|택시/i],
 ['harness','하네스·홀스터',/harness|holster|ハーネス|ホルスター|하네스|홀스터/i],
 ['seatbelt','시트벨트',/seat ?belt|シートベルト|시트벨트/i],['biker','바이커',/biker|moto\b|ライダース|バイカー|바이커/i],
 ['aviator','에비에이터',/aviator|アビエイター|에비에이터|아비에이터/i],
 ['ma1','MA-1',/ma-?1\b/i],['kite','카이트',/kite|カイト|카이트/i],['mohawk','모호크',/mohawk|モホーク|モヒカン|모호크|모히칸/i],
 ['reflective','리플렉티브',/reflective|\b3m\b|リフレクター|リフレクティブ|리플렉티브/i],
 ['resin','레진·러버',/resinat|rubberi|ラバーコーティング|ラバー加工|レジン加工|레진/i],
 ['sample','샘플·런웨이',/sample|runway|press|サンプル|ランウェイ|샘플|런웨이/i],
 ['deadstock','데드스톡',/deadstock|\bnwt\b|unworn|デッドストック|데드스톡/i]];
var LEX=[
 {m:'bondage',en:['bondage'],ja:['ボンデージ','ボンテージ'],ko:['본디지','본테지']},
 {m:'astro',en:['astro'],ja:['アストロ'],ko:['아스트로','애스트로']},
 {m:'flak',en:['flak','m69'],ja:['フラック'],ko:['플락']},
 {m:'bullet',en:['bulletproof','ballistic'],ja:['防弾','バリスティック'],ko:['방탄조끼','발리스틱']},
 {m:'painter',en:['painter'],ja:['ペインター'],ko:['페인터']},
 {m:'parachute',en:['parachute'],ja:['パラシュート'],ko:['파라슈트','낙하산']},
 {m:'taxi',en:['taxi'],ja:['タクシー'],ko:['택시']},
 {m:'harness',en:['harness','holster'],ja:['ハーネス','ホルスター'],ko:['하네스','홀스터']},
 {m:'seatbelt',en:['seatbelt'],ja:['シートベルト'],ko:['시트벨트']},
 {m:'biker',en:['biker','moto'],ja:['ライダース','バイカー'],ko:['바이커','라이더']},
 {m:'aviator',en:['aviator'],ja:['アビエイター'],ko:['에비에이터','아비에이터']},
 {m:'ma1',en:['ma-1','ma1'],ja:['ma-1'],ko:['ma-1']},
 {m:'kite',en:['kite'],ja:['カイト'],ko:['카이트']},
 {m:'mohawk',en:['mohawk'],ja:['モホーク','モヒカン'],ko:['모호크','모히칸']},
 {m:'reflective',en:['reflective','3m'],ja:['リフレクター','リフレクティブ'],ko:['리플렉티브','반사']},
 {m:'resin',en:['resin','rubber'],ja:['ラバー','レジン'],ko:['레진','러버']},
 {m:'sample',en:['sample','runway'],ja:['サンプル','ランウェイ'],ko:['샘플','런웨이']},
 {m:'deadstock',en:['deadstock','nwt','unworn'],ja:['デッドストック'],ko:['데드스톡']},
 {c:'데님',en:['denim','jeans'],ja:['デニム','ジーンズ'],ko:['데님','청바지']},
 {c:'팬츠',en:['pants','trousers'],ja:['パンツ','スラックス'],ko:['팬츠','바지','슬랙스']},
 {c:'테일러링',en:['tailored','blazer'],ja:['テーラード','ブレザー'],ko:['테일러드','블레이저']},
 {en:['suit'],ja:['スーツ'],ko:['수트','정장']},
 {en:['jacket'],ja:['ジャケット'],ko:['자켓','재킷']},
 {en:['coat'],ja:['コート'],ko:['코트']},
 {en:['hoodie','hooded'],ja:['フーディ','パーカー'],ko:['후드','후디']},
 {en:['shirt'],ja:['シャツ'],ko:['셔츠']},
 {en:['t-shirt','tee'],ja:['tシャツ'],ko:['티셔츠','반팔']},
 {en:['knit','sweater'],ja:['ニット','セーター'],ko:['니트','스웨터']},
 {en:['vest','gilet'],ja:['ベスト'],ko:['베스트','조끼']},
 {en:['leather'],ja:['レザー','革'],ko:['레더','가죽']},
 {en:['nylon'],ja:['ナイロン'],ko:['나일론']},
 {en:['boots'],ja:['ブーツ'],ko:['부츠']},
 {en:['sneakers'],ja:['スニーカー'],ko:['스니커즈']},
 {en:['bag'],ja:['バッグ'],ko:['가방']},
 {en:['belt'],ja:['ベルト'],ko:['벨트']},
 {en:['dress'],ja:['ワンピース','ドレス'],ko:['원피스','드레스']},
 {en:['skirt'],ja:['スカート'],ko:['스커트','치마']},
 {en:['bomber'],ja:['ボンバー'],ko:['봄버']},
 {en:['cargo'],ja:['カーゴ'],ko:['카고']},
 {en:['parka'],ko:['파카']},
 {en:['shearling','mouton'],ja:['ムートン'],ko:['무스탕','시어링']},
 {en:['cardigan'],ja:['カーディガン'],ko:['가디건']},
 {en:['archive'],ja:['アーカイブ'],ko:['아카이브']},
 {en:['vintage'],ja:['ヴィンテージ','ビンテージ','古着'],ko:['빈티지']},
 {en:['90s'],ja:['90年代'],ko:['90년대']},
 {ja:['本人期','初期'],ko:['본인기']},
 {en:['italy'],ja:['イタリア製','イタリア'],ko:['이탈리아']},
 {en:['austria'],ja:['オーストリア製','オーストリア'],ko:['오스트리아']}
];
var BRANDNOISE=['helmut','lang','helmutlang','ヘルムート','ラング','ヘルムートラング','헬무트','랭','헬무트랭','헬뭍랭','헬뭇랭'];
function nrm(x){
  x=String(x==null?'':x);
  try{ x=x.normalize('NFKC') }catch(e){}
  return x.toLowerCase().replace(/[\u2018\u2019'`]/g,'').replace(/\s+/g,' ').trim();
}
var LEXW={};
(function(){
  for(var r=0;r<LEX.length;r++){ var row=LEX[r];
    ['en','ja','ko'].forEach(function(L){ (row[L]||[]).forEach(function(w){
      var k=nrm(w); (LEXW[k]=LEXW[k]||[]).push(row) }) });
  }
})();
function alts(t){
  var rows=Object.prototype.hasOwnProperty.call(LEXW,t)?LEXW[t]:null, out=[t];
  if(rows) rows.forEach(function(row){ ['en','ja','ko'].forEach(function(L){
    (row[L]||[]).forEach(function(w){ w=nrm(w); if(out.indexOf(w)<0) out.push(w) }) }) });
  return out;
}
var PRICE=[['~30만',0,300000],['30–100만',300000,1000000],['100–300만',1000000,3000000],['300만~',3000000,Infinity]];
var CERT={A:'연도 표기',B:'아카이브 표기',C:'연도 미확인'};
var FLAGLBL={'new':'신규','drop':'가격 내림','multi':'여러 곳 등록','saved':'저장함','gone':'사라진 매물',
  'since':'지난 방문 이후','sold':'판매 기록','mine':'내 사이즈'};
var CATORDER=['아우터','데님','팬츠','상의','테일러링','신발','가방·액세서리','기타'];
var GRP={y:'연도',cat:'분류',motif:'모티프',price:'가격',src:'판매처',cert:'연도 근거',mark:'생산지·라인',flag:''};
var MARK=[
 ['italy','Made in Italy',/made\s*in\s*italy|\bitaly[\s-]*made\b|イタリア製|이탈리아\s*제|이태리\s*제/i],
 ['austria','Made in Austria',/made\s*in\s*austria|\baustria[\s-]*made\b|オーストリア製|오스트리아\s*제/i],
 ['usa','Made in USA',/made\s*in\s*(?:the\s*)?(?:u\.?s\.?a\b\.?|u\.?s\b\.?|united\s*states)|\busa[\s-]*made\b|アメリカ製|米国製/i],
 ['japan','Made in Japan',/made\s*in\s*japan|\bjapan[\s-]*made\b|日本製/i],
 ['portugal','Made in Portugal',/made\s*in\s*portugal|\bportugal[\s-]*made\b|ポルトガル製/i],
 ['jeans','Helmut Lang Jeans',null],
 ['mainline','Mainline',/\bmain[\s-]*line\b|メインライン/i]];
var MARKLBL={};
MARK.forEach(function(m){ MARKLBL[m[0]]=m[1] });
var HLJ=/helmut\s*lang\s*jeans\b|ヘルムート\s*ラング\s*ジーンズ/i;
var NOTJEANS=/jacket|trucker|shirt|\btee\b|hood|sweat|crew\s*neck|polo|turtle|blouse|\btank\b|long\s*sleeve|jersey|fleece|knit|sweater|jumper|cardigan|\bvest\b|coat|parka|anorak|bomber|blazer|belt|\bbag\b|\bcap\b|\bhat\b|skirt|dress|overall|jumpsuit|ジャケット|シャツ|ベルト|バッグ/i;
function marksOf(t){
  var out=[];
  for(var i=0;i<MARK.length;i++){
    var m=MARK[i];
    if(m[0]==='jeans'){
      var h=HLJ.exec(t); if(!h) continue;
      var after=t.slice(h.index+h[0].length), rest=t.slice(0,h.index)+' '+after;
      // Trousers or shorts are the line's only when nothing says denim, and not
      // written straight after it: 'Jeans Pants' is how many sellers say jeans.
      var legs=/\bpants\b|\btrousers\b|\bshorts\b/i.test(rest) && !/denim/i.test(rest) &&
        !/^\s*(?:pants|trousers|shorts)\b/i.test(after);
      if(/\bjeans?\b|ジーンズ/i.test(rest) || NOTJEANS.test(rest) || legs) out.push('jeans');
    } else if(m[2].test(t)) out.push(m[0]);
  }
  return out;
}
var SZGRP={'아우터':'top','상의':'top','테일러링':'top','팬츠':'bot','데님':'bot','신발':'shoe'};
var SZNAME={top:'상의·아우터',bot:'하의',shoe:'신발'};
var LETTERS=['XXXS','XXS','XS','S','M','L','XL','XXL','XXXL'];
function oneSize(p,bottoms){
  var m;
  if(LETTERS.indexOf(p)>=0) return p;
  if(/^(?:ONE SIZE|ONESIZE|OS|FREE|F)$/.test(p)) return 'ONE SIZE';
  if((m=/^(?:IT|EU)\s*(\d{1,2}(?:\.5)?)$/.exec(p)) || (m=/^(\d{1,2}(?:\.5)?)\s*(?:IT|EU)$/.exec(p))) return m[1];
  if((m=/^(US|UK|FR|JP)\s*(\d{1,2}(?:\.5)?)$/.exec(p))) return m[1]+' '+m[2];
  if((m=/^(\d{1,2}(?:\.5)?)\s*(US|UK|FR|JP)$/.exec(p))) return m[2]+' '+m[1];
  if((m=/^(\d{2})\s*[SRL]$/.exec(p))) return m[1];
  if(bottoms){
    if((m=/^W\s*(\d{2})(?:\s*L\s*\d{2})?$/.exec(p)) || (m=/^(\d{2})\s*(?:[X×]\s*)?\d{2}$/.exec(p))) return m[1];
  }
  return p;
}
function sizeToks(it){
  var z=it.z; if(!z) return [];
  z=String(z); try{ z=z.normalize('NFKC') }catch(e){}
  z=z.toUpperCase().replace(/\s+/g,' ').trim().replace(/\s*INTERNATIONAL$/,'');
  var bottoms = SZGRP[it.s]==='bot' || it.s==='기타', out=[];
  z.split(/\s*\/\s*/).forEach(function(p){ if(!p) return; var t=oneSize(p,bottoms); if(t && out.indexOf(t)<0) out.push(t) });
  return out;
}
function curOf(u){ return u && u!=='KRW' ? String(u) : '' }
function dnum(s){ var m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s||''); 
  return m? Date.UTC(+m[1],+m[2]-1,+m[3])/86400000 : null }
function daysBetween(a,b){ var x=dnum(a),y=dnum(b); return (x==null||y==null)?null:y-x }
function seenDays(it){                 // how long we have been watching it
  var end = it.x&&it.ls ? it.ls : TODAY;
  var n = daysBetween(it.f,end);
  return n==null?null:n+1;
}
function seenText(it){
  var n=seenDays(it); if(n==null) return '';
  if(it.x) return n<2 ? '1일간 보임' : won(n)+'일간 보임';
  return n<2 ? '' : won(n)+'일째';
}
function md(d){ var m=/^\d{4}-(\d{2})-(\d{2})/.exec(d||''); return m?(+m[1])+'/'+(+m[2]):'' }
var AEQ={m:60000,h:3600000,d:86400000};
function aucLeft(it){
  if(!it.ae) return '';
  var t=Date.parse(it.ae); if(isNaN(t)) return '';
  var q=AEQ[it.aeq]?it.aeq:'d', unit=AEQ[q], ms=t-Date.now();
  if(ms<=-unit || (q==='m' && ms<=0)) return '마감';
  if(ms<=0) return '마감 무렵';
  if(q==='d'){ var dd=Math.floor(ms/86400000); return dd>=1 ? won(dd)+'일 남음' : '하루 안에 마감' }
  var h=Math.floor(ms/3600000);
  if(h<1) return '1시간 안에 마감';
  if(h<24) return won(h)+'시간 남음';
  return won(Math.floor(h/24))+'일 남음';
}
function aucText(it){
  var p=[];
  if(typeof it.ab==='number' && it.ab>=0) p.push('입찰 '+won(it.ab));
  var l=aucLeft(it); if(l) p.push(l);
  return p.join(' · ');
}
function endText(it){
  var t=Date.parse(it.ae||''); if(isNaN(t)) return '';
  var d=new Date(t), p=function(n){ return (n<10?'0':'')+n };
  var day=(d.getMonth()+1)+'/'+d.getDate();
  // a clock time only when the source gave one to the minute
  if(it.aeq!=='m') return day+' 무렵';
  return day+' '+p(d.getHours())+':'+p(d.getMinutes());
}
function buyeeUrl(u){
  var m;
  if((m=/^https?:\/\/(?:page\.)?auctions\.yahoo\.co\.jp\/jp\/auction\/([a-z]?\d+)/i.exec(u||'')))
    return 'https://buyee.jp/item/jdirectitems/auction/'+m[1]+'?lang=ko';
  if((m=/^https?:\/\/jp\.mercari\.com\/item\/(m\d+)/i.exec(u||'')))
    return 'https://buyee.jp/mercari/item/'+m[1]+'?lang=ko';
  return null;
}
function compsHtml(it){
  var c=it.sc; if(!c || !(c.n>0) || !(c.md>0)) return '';
  var nat=c.u && c.u!=='KRW', sym=SYM[c.u]||'';
  var f=function(v){ return nat ? sym+Number(v).toLocaleString('en-US') : '₩'+won(v) };
  return '<div class="sc"><span class="lbl">판매 기록</span><p>같은 모델 '+won(c.n)+'건 · 중앙값 '+f(c.md)+
    (nat && c.k>0 ? ' (₩'+won(c.k)+')' : '')+
    (c.lo>0 && c.hi>c.lo ? ' · '+f(c.lo)+'–'+f(c.hi) : '')+
    (c.d ? ' · '+esc(c.d) : '')+'</p></div>';
}
var DOMESTIC={'번개장터':1,'후루츠패밀리':1,'당근':1};
function usdOf(it){
  if(it.u==='USD' && it.p>0) return {v:it.p, exact:true};
  var r=D.rates && D.rates.USD;
  return r>0 && it.k>0 ? {v:it.k/r, exact:false} : null;
}
function dutyHtml(it){
  if(it.so || it.x || DOMESTIC[it.r]) return '';
  var u=usdOf(it); if(!u) return '';
  var v=u.v, say, why;
  // near a line the cents decide, so they are shown; elsewhere whole dollars
  // (a seller's own price is shown as the seller wrote it)
  var near=Math.abs(v-150)<1 || Math.abs(v-200)<1;
  var amt='US$'+(u.exact ? v.toLocaleString('en-US',{maximumFractionDigits:2})
                : near ? v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})
                : Math.round(v).toLocaleString('en-US'))+(u.exact?'':' 상당');
  if(v<=150){ say='면세 기준 이하'; why='판매가 기준' }
  else if(v<=200){ say='미국발 특송만 면세'; why='판매가 기준' }
  else { say='과세 대상'; why='면세 기준 US$150 · 미국발 특송 US$200' }
  // a converted price within a few percent of a line can land on either side
  if(!u.exact && (Math.abs(v-150)/150<0.05 || Math.abs(v-200)/200<0.05)) why+=' · 환율 따라 달라짐';
  return '<dt>통관</dt><dd>'+amt+' · '+say+' <span class="basis">'+why+'</span></dd>';
}
var QUAL={early:'초반',mid:'중반',late:'후반','前半':'초반','初頭':'초반','中頃':'중반','後半':'후반','末':'후반'};
function yearClaim(it){
  var e=it.e; if(!e || !/^(?:19|20)\d{2}$/.test(e)) return null;
  var t=it.t||''; try{ t=t.normalize('NFKC') }catch(x){}
  var AP="['’‘]?", S='\\s*'+AP+'\\s*s(?![a-z])(?!\\s*\\/\\s*s)';   // 90's · 90’s · 90s — not the first s of s/s
  var got=null, at=-1, len=0, m;
  // a span: 2001-2005 · 1998/99 · c.2001-2003
  m=(new RegExp('(?:^|[^0-9])('+e+')\\s*[-–—~〜～/]\\s*((?:19|20)\\d{2}|\\d{2})(?![0-9])','i')).exec(t);
  if(m){
    var y1=+e, b=m[2], y2=b.length===4?+b:(Math.floor(y1/100)*100+(+b));
    if(b.length===2 && y2<y1) y2+=100;
    var st=m.index+m[0].indexOf(e), tail=t.slice(m.index+m[0].length), head=t.slice(0,st);
    var season=/^\s*(?:a\/?w|f\/?w|秋冬|fall|winter)/i.test(tail) || /(?:a\/?w|f\/?w|秋冬|fall|winter)\s*$/i.test(head);
    if(y2>y1 && y2<=2005 && !season){ got={k:'rng', v:e+'–'+b}; at=st; len=m[0].length-(st-m.index) }
  }
  // a decade: 1990s · late 1990’s · 1990年代後半
  if(!got && /0$/.test(e)){
    m=(new RegExp('(?:\\b(early|mid|late)[\\s-]*)?(?:^|[^0-9])?('+e+')'+S,'i')).exec(t);
    if(m){ got={k:'dec', v:e+'년대'+(m[1]?' '+QUAL[m[1].toLowerCase()]:'')}; at=m.index; len=m[0].length }
    else if((m=(new RegExp(e+'\\s*(?:年代|년대)\\s*(前半|初頭|中頃|後半|末)?')).exec(t))){
      got={k:'dec', v:e+'년대'+(m[1]?' '+QUAL[m[1]]:'')}; at=m.index; len=m[0].length }
  }
  // approximate: circa 2004 · c. 1997 · ca.1997 · early 2000
  if(!got){
    m=(new RegExp('(?:\\bcirca|\\bca\\.?|\\bc\\.|\\bearly|\\bmid|\\blate)[\\s-]*('+e+')(?![0-9])','i')).exec(t);
    if(m){ got={k:'about', v:e+'년 무렵'}; at=m.index; len=m[0].length }
  }
  if(!got) return null;
  // the same year written once more on its own is a year after all
  var rest=t.slice(0,at)+' '+t.slice(at+len);
  var bare=new RegExp('(?:^|[^0-9])'+e+'(?![0-9])(?!'+S+')(?!\\s*(?:年代|년대))(?!\\s*[-–—~〜～/]\\s*\\d)','i');
  return bare.test(rest)?null:got;
}
var CLAIMBASIS={dec:'연대 표기', rng:'기간 표기', about:'대략적 연도 표기',
  bought:'구입 연도 표기', y2k:'Y2K 표기', lang:'시기 표기',
  arch:'아카이브 표기', multi:'여러 연도 표기'};
function yearOf(it){
  var e=it.__e!==undefined?it.__e:it.e;
  if(!e) return null;
  var m=/^(\d{4})$/.exec(e); if(m) return +m[1];
  var s=/^[A-Z]{2}(\d{2})$/.exec(e);
  if(s){var n=+s[1]; return n>=86?1900+n:2000+n}
  return null;
}
function priceBand(k){ for(var i=0;i<PRICE.length;i++) if(k>=PRICE[i][1]&&k<PRICE[i][2]) return PRICE[i][0];
  return PRICE[0][0] }
var own=Object.prototype.hasOwnProperty;
function keys(o){ var a=[],k; for(k in o) if(own.call(o,k)&&o[k]) a.push(k); return a }
function any(o){ for(var k in o) if(own.call(o,k)&&o[k]) return true; return false }
function motifLbl(k){ for(var i=0;i<MOTIF.length;i++) if(MOTIF[i][0]===k) return MOTIF[i][1]; return k }
var QT=[], QX=[];
function setQuery(q){
  F.q=q;
  QT=q?nrm(q).split(' ').filter(function(t){ return t && BRANDNOISE.indexOf(t)<0 }):[];
  QX=QT.map(alts);
}
function hit(it,t){
  var p=it.__t.indexOf(t);
  if(p>=0) return p===0?70:50;
  if(it.__mw.indexOf(t)>=0) return 30;
  if(it.__sec.indexOf(t)>=0) return 15;
  if(it.__meta.indexOf(t)>=0) return 8;
  return 0;
}
function score(it){
  if(!QT.length) return 0;
  var total=0;
  for(var i=0;i<QT.length;i++){
    // the word as typed, or the same thing in another of the three languages
    var best=hit(it,QT[i]), a=QX[i];
    for(var j=1;j<a.length;j++){ var tp=it.__t.indexOf(a[j]); if(tp>=0){ var h=tp===0?70:50; if(h>best) best=h } }
    if(!best) return 0;            // every token has to land somewhere
    total+=best;
  }
  // the whole phrase sitting in the title, in order, is the strongest signal
  if(QT.length>1 && it.__t.indexOf(QT.join(' '))>=0) total+=60;
  return total;
}
function matchedIn(it){
  var f={};
  for(var i=0;i<QT.length;i++){
    var best=hit(it,QT[i]), a=QX[i];
    for(var j=1;j<a.length;j++) if(it.__t.indexOf(a[j])>=0 && best<50) best=50;
    if(best>=50) f['상품명']=1;
    else if(best===30) f['모티프']=1;
    else if(best===15) f['분류']=1;
    else if(best===8) f['연도·판매처·사이즈']=1;
  }
  return Object.keys(f);
}
var SEEK=[
 ['일본','야후옥션','ja',function(q){return 'https://auctions.yahoo.co.jp/search/search?p='+encodeURIComponent(q)}],
 ['일본','야후옥션','ja',function(q){return 'https://auctions.yahoo.co.jp/closedsearch/closedsearch?p='+encodeURIComponent(q)},'낙찰가'],
 ['일본','메루카리','ja',function(q){return 'https://jp.mercari.com/search?keyword='+encodeURIComponent(q)}],
 ['일본','라쿠마','ja',function(q){return 'https://fril.jp/s?query='+encodeURIComponent(q)}],
 ['일본','2nd STREET','en',function(q){return 'https://www.2ndstreet.jp/search?keyword='+encodeURIComponent(q)}],
 ['일본','RAGTAG','en',function(q){return 'https://www.ragtag.jp/search?fr='+encodeURIComponent(q)}],
 ['일본','Buyee','ja',function(q){return 'https://buyee.jp/item/search/query/'+encodeURIComponent(q)+'?lang=ko'},'구매대행'],
 ['한국','후루츠패밀리','ko',function(q){return 'https://fruitsfamily.com/search/'+encodeURIComponent(q)}],
 ['한국','번개장터','ko',function(q){return 'https://m.bunjang.co.kr/search/products?q='+encodeURIComponent(q)}],
 ['한국','당근','ko',function(q){return 'https://www.daangn.com/kr/buy-sell/?search='+encodeURIComponent(q)}],
 ['해외','Grailed','en',function(q){return 'https://www.grailed.com/shop?query='+encodeURIComponent(q)}],
 ['해외','eBay','en',function(q){return 'https://www.ebay.com/sch/i.html?_nkw='+encodeURIComponent(q)}],
 ['해외','eBay','en',function(q){return 'https://www.ebay.com/sch/i.html?_nkw='+encodeURIComponent(q)+'&LH_Sold=1&LH_Complete=1'},'판매 완료'],
 ['해외','Depop','en',function(q){return 'https://www.depop.com/search/?q='+encodeURIComponent(q)}],
 ['해외','Vinted','en',function(q){return 'https://www.vinted.fr/catalog?search_text='+encodeURIComponent(q)},'유럽'],
 ['해외','Vinted','en',function(q){return 'https://www.vinted.com/catalog?search_text='+encodeURIComponent(q)},'미국'],
 ['해외','Vestiaire','en',function(q){return 'https://www.vestiairecollective.com/search/?q='+encodeURIComponent(q)}],
 ['해외','The RealReal','en',function(q){return 'https://www.therealreal.com/products?keywords='+encodeURIComponent(q)}],
 ['해외','1stDibs','en',function(q){return 'https://www.1stdibs.com/search/?q='+encodeURIComponent(q)}],
 ['해외','Poshmark','en',function(q){return 'https://poshmark.com/search?query='+encodeURIComponent(q)}]
];
var SEEKBRAND={en:'helmut lang',ja:'helmut lang',ko:'헬무트랭'};
var HANGUL=/[\uac00-\ud7a3]/, KANA=/[\u3040-\u30ff\u4e00-\u9fff]/;
function lexRow(pred){ for(var i=0;i<LEX.length;i++) if(pred(LEX[i])) return LEX[i]; return null }
function word(row,L){ return row && row[L] && row[L].length ? row[L][0] : null }
function seekParts(){
  var parts=[];
  for(var i=0;i<QT.length;i++){
    var rows=Object.prototype.hasOwnProperty.call(LEXW,QT[i])?LEXW[QT[i]]:null;
    parts.push(rows?{row:rows[0],typed:QT[i]}:{raw:QT[i]});
  }
  var mo=keys(F.motif); if(mo.length===1){ var r=lexRow(function(x){return x.m===mo[0]}); if(r) parts.push({row:r}) }
  var ca=keys(F.cat); if(ca.length===1){ var rc=lexRow(function(x){return x.c===ca[0]}); if(rc) parts.push({row:rc}) }
  var ys=keys(F.y).filter(function(y){return y!=='none'}); if(ys.length===1) parts.push({raw:ys[0]});
  return parts;
}
function seekQuery(parts,L){
  var w=[SEEKBRAND[L]];
  parts.forEach(function(p){
    // the typed word itself when it belongs to this language (suit stays suit,
    // it does not become blazer); the row's first word only to translate
    var inL = p.typed && p.row[L] && p.row[L].some(function(w){ return nrm(w)===p.typed });
    var t = inL ? p.typed : p.row ? word(p.row,L) : p.raw;
    if(!t) return;
    // a word in one script sent to a platform that reads another finds nothing
    if(!p.row){ if(HANGUL.test(t) && L!=='ko') return; if(KANA.test(t) && L!=='ja') return; }
    if(w.indexOf(t)<0) w.push(t);
  });
  return w.join(' ');
}
function flagsHtml(it){
  var h='';
  // A without a value: the seller wrote the season (a shop's tag, a form the
  // English reader certified but did not copy out) — it is not 연도 미확인
  if(it.__e) h+='<span>'+esc(it.__e)+'</span>';
  else if(it.__yc) h+='<span class="d">'+esc(it.__yc.k==='arch'?'아카이브 표기':it.__yc.v)+'</span>';
  else if(it.c==='A') h+='<span>연도 표기</span>';
  else if(it.c==='B') h+='<span class="d">아카이브 표기</span>';
  else h+='<span class="s">연도 미확인</span>';
  if(it.so) h+='<span class="d">'+esc(it.sk||'판매 완료')+'</span>';
  if(it.n && !ALLNEW) h+='<span>신규</span>';
  if(it.w && it.w>it.k) h+='<span class="d">가격 내림</span>';
  return h;
}
function priceHtml(it,big){
  var alt=(it.u&&it.p>0)?'<span class="alt">'+(SYM[it.u]||'')+Number(it.p).toLocaleString('en-US')+'</span>':'';
  var was=(it.w&&it.w>it.k)?'<span class="was">₩'+won(it.w)+'</span>':'';
  return '<div class="'+(big?'big':'p')+'">₩'+won(it.k)+(alt?' '+alt:'')+(was?' '+was:'')+'</div>';
}
function thumb(u,w){
  if(!u) return u;
  try{
    if(u.indexOf('media-assets.grailed.com')>=0) return u+(u.indexOf('?')<0?'?':'&')+'w='+w;
    if(u.indexOf('cdn.shopify.com')>=0)          return u+(u.indexOf('?')<0?'?':'&')+'width='+w;
    if(u.indexOf('i.ebayimg.com')>=0)            return u.replace(/\/s-l\d+\.(jpg|png|webp)/i,
      '/s-l'+(w<=160?225:w<=400?400:w<=800?500:1600)+'.$1');
    if(u.indexOf('images.vestiairecollective.com')>=0) return u.replace(/\bw=\d+/, 'w='+w);
  }catch(e){}
  return u;
}
function photosOf(it){
  var a=[];
  if(it.i) a.push(it.i);
  if(Array.isArray(it.im)) it.im.forEach(function(u){
    if(typeof u==='string' && /^https?:\/\//.test(u) && a.indexOf(u)<0) a.push(u) });
  return a.slice(0,12);
}
function histHtml(it){
  if(!it.h||it.h.length<2) return '';
  var cur=it.u||'', sym={USD:'$',GBP:'£',EUR:'€',JPY:'¥'}[cur]||'';
  var nat=function(pt){ return pt.length>2 && pt[2]>0 ? pt[2] : null };
  var haveNat=it.h.every(function(pt){ return nat(pt)!=null });
  // For a listing priced in another currency, the won figure alone cannot say
  // whether the seller moved: the rate moves it too. Points recorded before
  // the seller's price was kept carry only won, and for those we show the
  // dates and what we converted, and say nothing about direction.
  var krwIsSeller = !cur || cur==='KRW';
  var canJudge = haveNat || krwIsSeller;
  var rows=it.h.map(function(pt,i){
    var d=pt[0], v=pt[1], p=nat(pt);
    var pv=i>0?it.h[i-1]:null;
    // compare like with like: seller's number if both ends have one
    var a = haveNat&&pv ? nat(pv) : (pv?pv[1]:null);
    var b = haveNat ? p : v;
    var delta='';
    if(canJudge && a!=null && b!==a) delta='<em class="'+(b<a?'dn':'up')+'">'+
      (b<a?'−':'+')+(haveNat?sym+Number(Math.abs(b-a)).toLocaleString('en-US'):won(Math.abs(b-a)))+'</em>';
    var alt = (haveNat && sym) ? '<span class="alt">'+sym+Number(p).toLocaleString('en-US')+'</span>' : '';
    return '<div><span>'+esc(d)+'</span><b>₩'+won(v)+alt+delta+'</b></div>';
  }).join('');
  var f0=it.h[0], l0=it.h[it.h.length-1];
  var first = haveNat ? nat(f0) : f0[1], last = haveNat ? nat(l0) : l0[1];
  var net='';
  if(!canJudge){
    net='<div class="net">원화 환산가만 기록됨</div>';
  } else if(first!==last && first>0){
    var amt = haveNat ? sym+Number(Math.abs(last-first)).toLocaleString('en-US') : won(Math.abs(last-first));
    net='<div class="net">'+(last<first?'내림 ':'오름 ')+amt+' · '+
      (Math.abs(last-first)/first*100).toFixed(1).replace(/\.0$/,'')+'%</div>';
  }
  return '<div class="hist"><span class="lbl">가격 변동</span>'+rows+net+'</div>';
}
function keyOf(it){
  if(it.__k) return it.__k;
  var h=0x811c9dc5, u=it.l||'';
  for(var i=0;i<u.length;i++){ h^=u.charCodeAt(i); h=Math.imul(h,0x01000193)>>>0 }
  return (it.__k=h.toString(36));
}
var CATSLUG={'아우터':'outer','데님':'denim','팬츠':'pants','상의':'tops',
  '테일러링':'tailoring','신발':'shoes','가방·액세서리':'bags','기타':'other'};
var PRICESLUG={'~30만':'under-300k','30–100만':'300k-1m','100–300만':'1m-3m','300만~':'over-3m'};
var CERTSLUG={A:'confirmed',B:'archive',C:'unknown'};
function packYears(ks){
  var ns=ks.filter(function(k){return /^\d{4}$/.test(k)}).map(Number).sort(function(a,b){return a-b});
  var rest=ks.filter(function(k){return !/^\d{4}$/.test(k)});
  var out=[],i=0;
  while(i<ns.length){
    var j=i; while(j+1<ns.length && ns[j+1]===ns[j]+1) j++;
    out.push(j>i?ns[i]+'-'+ns[j]:String(ns[i])); i=j+1;
  }
  return out.concat(rest);
}
function unpackYears(parts){
  var out=[];
  parts.forEach(function(p){
    var m=/^(\d{4})-(\d{4})$/.exec(p);
    if(m){ var a=+m[1],b=+m[2]; if(b<a){var t=a;a=b;b=t}
      for(var y=a;y<=Math.min(b,2005);y++) out.push(String(y)); }
    else out.push(p);
  });
  return out;
}
/* ---- end of copy ---- */
function prep(it){
  var ycE=yearClaim(it);
  it.__yc=ycE || (it.q ? {k:it.qk||'arch', v:it.q} : null);
  it.__e=ycE?null:(it.e||null);
  it.__c=ycE?'B':(it.__e?'A':it.c);
  it.__y=yearOf(it);
  it.__yk=it.__y?String(it.__y):'none';
  it.__m=[]; var mw='';
  var tk=it.t||''; try{ tk=tk.normalize('NFKC') }catch(e){}
  for(var j=0;j<MOTIF.length;j++) if(MOTIF[j][2].test(tk)){ it.__m.push(MOTIF[j][0]); mw+=' '+MOTIF[j][0]+' '+MOTIF[j][1] }
  it.__mk=marksOf(tk,it);
  it.__z=sizeToks(it);
  it.__t=nrm(it.t);
  it.__mw=nrm(mw);
  it.__sec=nrm(it.s);
  it.__meta=nrm((it.e||'')+' '+(it.r||'')+' '+(it.z||''));
  it.__s=it.__t+' '+it.__mw+' '+it.__sec+' '+it.__meta;
}
return {tag:'hl', won:won, SYM:SYM, esc:esc, MOTIF:MOTIF, LEX:LEX, BRANDNOISE:BRANDNOISE, nrm:nrm, LEXW:LEXW, alts:alts, PRICE:PRICE, CERT:CERT, FLAGLBL:FLAGLBL, CATORDER:CATORDER, GRP:GRP, MARK:MARK, MARKLBL:MARKLBL, HLJ:HLJ, NOTJEANS:NOTJEANS, marksOf:marksOf, SZGRP:SZGRP, SZNAME:SZNAME, LETTERS:LETTERS, oneSize:oneSize, sizeToks:sizeToks, curOf:curOf, dnum:dnum, daysBetween:daysBetween, seenDays:seenDays, seenText:seenText, md:md, AEQ:AEQ, aucLeft:aucLeft, aucText:aucText, endText:endText, buyeeUrl:buyeeUrl, compsHtml:compsHtml, DOMESTIC:DOMESTIC, usdOf:usdOf, dutyHtml:dutyHtml, QUAL:QUAL, yearClaim:yearClaim, CLAIMBASIS:CLAIMBASIS, yearOf:yearOf, priceBand:priceBand, keys:keys, any:any, motifLbl:motifLbl, setQuery:setQuery, hit:hit, score:score, matchedIn:matchedIn, SEEK:SEEK, SEEKBRAND:SEEKBRAND, HANGUL:HANGUL, lexRow:lexRow, word:word, seekParts:seekParts, seekQuery:seekQuery, thumb:thumb, photosOf:photosOf, histHtml:histHtml, keyOf:keyOf, CATSLUG:CATSLUG, PRICESLUG:PRICESLUG, CERTSLUG:CERTSLUG, packYears:packYears, unpackYears:unpackYears, flagsHtml:flagsHtml, priceHtml:priceHtml,
  prep:prep,
  setData:function(d){ D=d; TODAY=d.today||null; var c=d.counts||{}; ALLNEW=!!(c.items && c.fresh>=c.items) },
  setF:function(f){ F=f },
  setSince:function(s){ SINCE=s },
  getQT:function(){ return QT.slice() },
  hasCodes:false};
})();

AIX.profiles.ccp=(function(){
'use strict';
var D=null, TODAY=null, SINCE=null, saved={}, ALLNEW=false;
var F={y:{},cat:{},motif:{},price:{},src:{},cert:{},mark:{},flag:{},size:'',q:''};
/* ---- copied from ccp template.html (repo main) ---- */
var won=function(n){return Number(n||0).toLocaleString('ko-KR')};
var SYM={USD:'$',GBP:'£',EUR:'€',JPY:'¥',KRW:'₩',CAD:'CA$',AUD:'A$',NZD:'NZ$',HKD:'HK$',SGD:'S$',CNY:'CN¥',CHF:'CHF ',
  SEK:'SEK ',DKK:'DKK ',NOK:'NOK ',PLN:'PLN ',CZK:'CZK ',HUF:'HUF ',THB:'THB ',MXN:'MX$',BRL:'R$',INR:'₹',TRY:'TRY '};
var esc=function(s){return String(s==null?'':s).replace(/[&<>"]/g,function(c){
  return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})};
var MOTIF=[['drip','드립',/drip|ドリップ|드립/i],
 ['objectdyed','오브젝트 다이드',/object[\s-]*dy(?:ed|e)|\bo\.d\.(?=\s|$|["'“”])|製品染め|オブジェクトダイ|오브젝트\s*다이/i],
 ['overlock','오버록',/over[\s-]*lock|オーバーロック|오버록/i],
 ['deadend','데드엔드',/dead[\s-]*end|デッドエンド|데드\s*[엔앤]드/i],
 ['chainseam','체인 심',/chain[\s-]*(?:seam|stitch)|チェーン\s*(?:シーム|ステッチ)|체인\s*(?:심|스티치)/i],
 ['scarstitch','스카 스티치',/scar[\s-]*stitch|スカー\s*ステッチ|스카\s*스티치/i],
 ['seamless','심리스',/seamless|no[\s-]?seam|シームレス|심리스/i],
 ['reversible','리버시블',/reversible|リバーシブル|리버시블/i],
 ['spiral','스파이럴',/spiral|スパイラル|스파이럴/i],
 ['inbetween','인비트윈',/in[\s-]*between|インビトウィーン|인비트윈/i],
 ['prosthetic','프로스테틱',/prosthetic|プロステティック|프로스테틱/i],
 ['tornado','토네이도',/tornado|トルネード|토네이도/i],
 ['diagonalzip','다이애거널 지퍼',/diagonal[\s-]*zip|ダイアゴナル|다이[애아]고?[널날]/i],
 ['usole','U솔',/(?<![a-z])u[\s-]*sole|uソール|u\s*솔/i],
 ['paperdart','페이퍼 다트',/paper[\s-]*dart|ペーパーダート|페이퍼\s*다트/i],
 ['goodyear','굿이어',/good[\s-]*year|グッドイヤー|굿이어/i],
 ['officer','오피서',/officer|オフィサー|오피서/i],
 ['highneck','하이넥',/high[\s-]*neck|ハイネック|하이넥/i],
 ['vestbag','베스트 백',/vest[\s-]*bag|ベストバッグ|베스트\s*백/i],
 ['sample','샘플·런웨이',/sample|runway|サンプル|ランウェイ|샘플|런웨이/i]];
var LEX=[
 {m:'drip',en:['drip'],ja:['ドリップ'],ko:['드립']},
 {m:'objectdyed',en:['object dyed'],ja:['製品染め'],ko:['오브젝트 다이드']},
 {m:'overlock',en:['overlock'],ja:['オーバーロック'],ko:['오버록']},
 {m:'deadend',en:['dead end','deadend'],ja:['デッドエンド'],ko:['데드엔드']},
 {m:'chainseam',en:['chain seam','chainseam'],ko:['체인 심']},
 {m:'scarstitch',en:['scar stitch'],ko:['스카스티치']},
 {m:'seamless',en:['seamless'],ja:['シームレス'],ko:['심리스']},
 {m:'reversible',en:['reversible'],ja:['リバーシブル'],ko:['리버시블']},
 {m:'spiral',en:['spiral'],ja:['スパイラル'],ko:['스파이럴']},
 {m:'inbetween',en:['in-between'],ko:['인비트윈']},
 {m:'prosthetic',en:['prosthetic'],ja:['プロステティック'],ko:['프로스테틱']},
 {m:'tornado',en:['tornado'],ja:['トルネード'],ko:['토네이도']},
 {m:'diagonalzip',en:['diagonal zip'],ja:['ダイアゴナル'],ko:['다이애거널']},
 {m:'usole',en:['u-sole','u sole'],ja:['uソール'],ko:['u솔']},
 {m:'paperdart',en:['paper dart','paperdart'],ja:['ペーパーダート'],ko:['페이퍼 다트']},
 {m:'goodyear',en:['goodyear'],ja:['グッドイヤー'],ko:['굿이어']},
 {m:'officer',en:['officer'],ja:['オフィサー'],ko:['오피서']},
 {m:'highneck',en:['high neck','highneck'],ja:['ハイネック'],ko:['하이넥']},
 {m:'vestbag',en:['vest bag'],ja:['ベストバッグ'],ko:['베스트백']},
 {m:'sample',en:['sample','runway'],ja:['サンプル','ランウェイ'],ko:['샘플','런웨이']},
 {c:'신발',en:['boots','boot'],ja:['ブーツ'],ko:['부츠']},
 {c:'셔츠',en:['shirt'],ja:['シャツ'],ko:['셔츠']},
 {c:'상의',en:['knit','sweater'],ja:['ニット','セーター'],ko:['니트','스웨터']},
 {c:'아우터',en:['jacket'],ja:['ジャケット'],ko:['자켓','재킷']},
 {c:'데님',en:['denim','jeans'],ja:['デニム','ジーンズ'],ko:['데님','청바지']},
 {c:'팬츠',en:['pants','trousers'],ja:['パンツ','スラックス','トラウザー'],ko:['팬츠','바지','슬랙스','트라우저']},
 {c:'테일러링',en:['tailored','blazer'],ja:['テーラード','ブレザー'],ko:['테일러드','블레이저']},
 {c:'가방·소품',en:['bag'],ja:['バッグ'],ko:['가방']},
 {c:'주얼리',en:['ring'],ja:['リング','指輪'],ko:['반지','링']},
 {en:['sneakers','sneaker'],ja:['スニーカー'],ko:['스니커즈']},
 {en:['derby','derbys','shoes'],ja:['ダービー','シューズ'],ko:['더비','구두']},
 {en:['sandals'],ja:['サンダル'],ko:['샌들']},
 {en:['coat'],ja:['コート'],ko:['코트']},
 {en:['parka'],ja:['パーカ'],ko:['파카']},
 {en:['vest','gilet'],ja:['ベスト','ジレ'],ko:['베스트','조끼']},
 {en:['suit','setup'],ja:['スーツ','セットアップ'],ko:['수트','셋업']},
 {en:['t-shirt','tee'],ja:['tシャツ','カットソー'],ko:['티셔츠','반팔']},
 {en:['cardigan'],ja:['カーディガン'],ko:['가디건']},
 {en:['hoodie'],ja:['フーディ','パーカー'],ko:['후드']},
 {en:['necklace'],ja:['ネックレス'],ko:['목걸이']},
 {en:['bracelet'],ja:['ブレスレット'],ko:['팔찌']},
 {en:['belt'],ja:['ベルト'],ko:['벨트']},
 {en:['gloves','glove'],ja:['グローブ','手袋'],ko:['장갑']},
 {en:['wallet'],ja:['財布','ウォレット'],ko:['지갑']},
 {en:['leather'],ja:['レザー','革'],ko:['레더','가죽']},
 {en:['kangaroo'],ja:['カンガルー'],ko:['캥거루']},
 {en:['horse'],ja:['ホース','馬革'],ko:['홀스']},
 {en:['cordovan'],ja:['コードバン'],ko:['코도반']},
 {en:['titanium'],ja:['チタン'],ko:['티타늄']},
 {en:['silver'],ja:['シルバー'],ko:['실버']},
 {en:['rubber'],ja:['ラバー'],ko:['러버']},
 {en:['wool'],ja:['ウール'],ko:['울']},
 {en:['cotton'],ja:['コットン'],ko:['코튼']},
 {en:['linen'],ja:['リネン'],ko:['린넨']},
 {en:['ramie'],ja:['ラミー'],ko:['라미']},
 {en:['black'],ja:['ブラック','黒'],ko:['블랙']},
 {en:['white'],ja:['ホワイト','白'],ko:['화이트']},
 {en:['archive'],ja:['アーカイブ'],ko:['아카이브']},
 {en:['vintage'],ja:['ヴィンテージ','ビンテージ','古着'],ko:['빈티지']},
 {en:['90s'],ja:['90年代'],ko:['90년대']},
 {en:['early'],ja:['初期'],ko:['초기']},
 {en:['new'],ja:['新品','未使用'],ko:['새상품','미착용']},
 {en:['italy'],ja:['イタリア製','イタリア'],ko:['이탈리아']}
];
var BRANDNOISE=['carol','christian','poell','poel','carolchristianpoell','ccp','c.c.p','c.c.p.','キャロル','クリスチャン','ポエル',
  'キャロルクリスチャンポエル','캐롤','크리스찬','크리스챤','포엘','캐롤크리스찬포엘','캐롤크리스챤포엘'];
function codeForms(c){
  var m=/^(?:([A-Z]{1,2})\/)?(\d{4})([A-Z]{0,2})$/.exec(String(c||'').toUpperCase()); if(!m) return '';
  var p=(m[1]||'').toLowerCase(), n=m[2], x=(m[3]||'').toLowerCase(), out=[n, n+x];
  if(p) out.push(p+'/'+n, p+n, p+'/'+n+x, p+n+x);
  return out.join(' ');
}
function codeNum(c){ var m=/(\d{4})/.exec(c||''); return m?m[1]:'' }
var MAXY=new Date().getFullYear()+1, YMIN=1995, YMAX=MAXY;
function nrm(x){
  x=String(x==null?'':x);
  try{ x=x.normalize('NFKC') }catch(e){}
  return x.toLowerCase().replace(/[\u2018\u2019'`]/g,'').replace(/\s+/g,' ').trim();
}
var LEXW={};
(function(){
  for(var r=0;r<LEX.length;r++){ var row=LEX[r];
    ['en','ja','ko'].forEach(function(L){ (row[L]||[]).forEach(function(w){
      var k=nrm(w); (LEXW[k]=LEXW[k]||[]).push(row) }) });
  }
})();
function alts(t){
  var rows=Object.prototype.hasOwnProperty.call(LEXW,t)?LEXW[t]:null, out=[t];
  if(rows) rows.forEach(function(row){ ['en','ja','ko'].forEach(function(L){
    (row[L]||[]).forEach(function(w){ w=nrm(w); if(out.indexOf(w)<0) out.push(w) }) }) });
  return out;
}
var PRICE=[['~50만',0,500000],['50–150만',500000,1500000],['150–300만',1500000,3000000],['300만~',3000000,Infinity]];
var CERT={A:'연도 표기',B:'시기 표기',C:'연도 미확인'};
var FLAGLBL={'new':'신규','drop':'가격 내림','multi':'여러 곳 등록','saved':'저장함','gone':'사라진 매물',
  'since':'지난 방문 이후','sold':'판매 기록','mine':'내 사이즈'};
var CATORDER=['아우터','테일러링','셔츠','상의','팬츠','데님','신발','가방·소품','주얼리','기타'];
var GRP={y:'연도',cat:'분류',motif:'기법·모델',price:'가격',src:'판매처',cert:'연도 근거',mark:'소재·표기',flag:''};
var MARK=[
 ['kangaroo','캥거루',/kangaroo|garoo|カンガルー|캥거루/i],
 ['horse','홀스',/horse|ホース\s*(?:レザー|ハイド)|馬革|홀스|말가죽/i],
 ['cordovan','코도반',/cordovan|コードバン|코도반/i],
 ['bison','바이슨',/bison|バイソン|바이슨/i],
 ['titanium','티타늄',/titanium|チタン|티타늄/i],
 ['new','새 상품',/新品(?!\s*同様|\s*に近い)|未使用(?!\s*に近い)|未着用|デッドストック|deadstock|\bbnwt\b|\bnwt\b|new\s*with\s*tags|unworn|새상품|새\s*상품|미착용/i],
 ['italy','Made in Italy',/made\s*in\s*italy|\bitaly[\s-]*made\b|イタリア製|이탈리아\s*제|이태리\s*제/i]];
var MARKLBL={};
MARK.forEach(function(m){ MARKLBL[m[0]]=m[1] });
function marksOf(t,it){
  var out=[];
  for(var i=0;i<MARK.length;i++) if(MARK[i][2].test(t)) out.push(MARK[i][0]);
  if(it && it.cn==='new' && out.indexOf('new')<0) out.push('new');
  return out;
}
var SZGRP={'아우터':'top','테일러링':'top','셔츠':'top','상의':'top','팬츠':'bot','데님':'bot','신발':'shoe'};
var SZNAME={top:'상의·아우터',bot:'하의',shoe:'신발'};
var LETTERS=['XXXS','XXS','XS','S','M','L','XL','XXL','XXXL'];
function oneSize(p,bottoms){
  var m;
  if(LETTERS.indexOf(p)>=0) return p;
  if(/^(?:ONE SIZE|ONESIZE|OS|FREE|F)$/.test(p)) return 'ONE SIZE';
  if((m=/^(?:IT|EU)\s*(\d{1,2}(?:\.5)?)$/.exec(p)) || (m=/^(\d{1,2}(?:\.5)?)\s*(?:IT|EU)$/.exec(p))) return m[1];
  if((m=/^(US|UK|FR|JP)\s*(\d{1,2}(?:\.5)?)$/.exec(p))) return m[1]+' '+m[2];
  if((m=/^(\d{1,2}(?:\.5)?)\s*(US|UK|FR|JP)$/.exec(p))) return m[2]+' '+m[1];
  if((m=/^(\d{2})\s*[SRL]$/.exec(p))) return m[1];
  if(bottoms){
    if((m=/^W\s*(\d{2})(?:\s*L\s*\d{2})?$/.exec(p)) || (m=/^(\d{2})\s*(?:[X×]\s*)?\d{2}$/.exec(p))) return m[1];
  }
  return p;
}
function sizeToks(it){
  var z=it.z; if(!z) return [];
  z=String(z); try{ z=z.normalize('NFKC') }catch(e){}
  z=z.toUpperCase().replace(/\s+/g,' ').trim().replace(/\s*INTERNATIONAL$/,'');
  var bottoms = SZGRP[it.s]==='bot' || it.s==='기타', out=[];
  z.split(/\s*\/\s*/).forEach(function(p){ if(!p) return; var t=oneSize(p,bottoms); if(t && out.indexOf(t)<0) out.push(t) });
  return out;
}
function curOf(u){ return u && u!=='KRW' ? String(u) : '' }
function dnum(s){ var m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s||''); 
  return m? Date.UTC(+m[1],+m[2]-1,+m[3])/86400000 : null }
function daysBetween(a,b){ var x=dnum(a),y=dnum(b); return (x==null||y==null)?null:y-x }
function seenDays(it){                 // how long we have been watching it
  var end = it.x&&it.ls ? it.ls : TODAY;
  var n = daysBetween(it.f,end);
  return n==null?null:n+1;
}
function seenText(it){
  var n=seenDays(it); if(n==null) return '';
  if(it.x) return n<2 ? '1일간 보임' : won(n)+'일간 보임';
  return n<2 ? '' : won(n)+'일째';
}
function md(d){ var m=/^\d{4}-(\d{2})-(\d{2})/.exec(d||''); return m?(+m[1])+'/'+(+m[2]):'' }
var AEQ={m:60000,h:3600000,d:86400000};
function aucLeft(it){
  if(!it.ae) return '';
  var t=Date.parse(it.ae); if(isNaN(t)) return '';
  var q=AEQ[it.aeq]?it.aeq:'d', unit=AEQ[q], ms=t-Date.now();
  if(ms<=-unit || (q==='m' && ms<=0)) return '마감';
  if(ms<=0) return '마감 무렵';
  if(q==='d'){ var dd=Math.floor(ms/86400000); return dd>=1 ? won(dd)+'일 남음' : '하루 안에 마감' }
  var h=Math.floor(ms/3600000);
  if(h<1) return '1시간 안에 마감';
  if(h<24) return won(h)+'시간 남음';
  return won(Math.floor(h/24))+'일 남음';
}
function aucText(it){
  var p=[];
  if(typeof it.ab==='number' && it.ab>=0) p.push('입찰 '+won(it.ab));
  var l=aucLeft(it); if(l) p.push(l);
  return p.join(' · ');
}
function endText(it){
  var t=Date.parse(it.ae||''); if(isNaN(t)) return '';
  var d=new Date(t), p=function(n){ return (n<10?'0':'')+n };
  var day=(d.getMonth()+1)+'/'+d.getDate();
  // a clock time only when the source gave one to the minute
  if(it.aeq!=='m') return day+' 무렵';
  return day+' '+p(d.getHours())+':'+p(d.getMinutes());
}
function buyeeUrl(u){
  var m;
  if((m=/^https?:\/\/(?:page\.)?auctions\.yahoo\.co\.jp\/jp\/auction\/([a-z]?\d+)/i.exec(u||'')))
    return 'https://buyee.jp/item/jdirectitems/auction/'+m[1]+'?lang=ko';
  if((m=/^https?:\/\/jp\.mercari\.com\/item\/(m\d+)/i.exec(u||'')))
    return 'https://buyee.jp/mercari/item/'+m[1]+'?lang=ko';
  return null;
}
function compsHtml(it){
  var c=it.sc; if(!c || !(c.n>0) || !(c.md>0)) return '';
  var nat=c.u && c.u!=='KRW', sym=SYM[c.u]||'';
  var f=function(v){ return nat ? sym+Number(v).toLocaleString('en-US') : '₩'+won(v) };
  return '<div class="sc"><span class="lbl">판매 기록</span><p>'+(c.b==='code'?'같은 번호 ':'같은 모델 ')+won(c.n)+'건 · 중앙값 '+f(c.md)+
    (nat && c.k>0 ? ' (₩'+won(c.k)+')' : '')+
    (c.lo>0 && c.hi>c.lo ? ' · '+f(c.lo)+'–'+f(c.hi) : '')+
    (c.d ? ' · '+esc(c.d) : '')+'</p></div>';
}
var DOMESTIC={'번개장터':1,'후루츠패밀리':1};
function usdOf(it){
  if(it.u==='USD' && it.p>0) return {v:it.p, exact:true};
  var r=D.rates && D.rates.USD;
  return r>0 && it.k>0 ? {v:it.k/r, exact:false} : null;
}
function dutyHtml(it){
  if(it.so || it.x || DOMESTIC[it.r]) return '';
  var u=usdOf(it); if(!u) return '';
  var v=u.v, say, why;
  // near a line the cents decide, so they are shown; elsewhere whole dollars
  // (a seller's own price is shown as the seller wrote it)
  var near=Math.abs(v-150)<1 || Math.abs(v-200)<1;
  var amt='US$'+(u.exact ? v.toLocaleString('en-US',{maximumFractionDigits:2})
                : near ? v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})
                : Math.round(v).toLocaleString('en-US'))+(u.exact?'':' 상당');
  if(v<=150){ say='면세 기준 이하'; why='판매가 기준' }
  else if(v<=200){ say='미국발 특송만 면세'; why='판매가 기준' }
  else { say='과세 대상'; why='면세 기준 US$150 · 미국발 특송 US$200' }
  // a converted price within a few percent of a line can land on either side
  if(!u.exact && (Math.abs(v-150)/150<0.05 || Math.abs(v-200)/200<0.05)) why+=' · 환율 따라 달라짐';
  return '<dt>통관</dt><dd>'+amt+' · '+say+' <span class="basis">'+why+'</span></dd>';
}
var QUAL={early:'초반',mid:'중반',late:'후반','前半':'초반','初頭':'초반','中頃':'중반','後半':'후반','末':'후반'};
function yearClaim(it){
  var e=it.e; if(!e || !/^(?:19|20)\d{2}$/.test(e)) return null;
  var t=it.t||''; try{ t=t.normalize('NFKC') }catch(x){}
  var AP="['’‘]?", S='\\s*'+AP+'\\s*s(?![a-z])(?!\\s*\\/\\s*s)';   // 90's · 90’s · 90s — not the first s of s/s
  var got=null, at=-1, len=0, m;
  // a span: 2001-2005 · 1998/99 · c.2001-2003
  m=(new RegExp('(?:^|[^0-9])('+e+')\\s*[-–—~〜～/]\\s*((?:19|20)\\d{2}|\\d{2})(?![0-9])','i')).exec(t);
  if(m){
    var y1=+e, b=m[2], y2=b.length===4?+b:(Math.floor(y1/100)*100+(+b));
    if(b.length===2 && y2<y1) y2+=100;
    var st=m.index+m[0].indexOf(e), tail=t.slice(m.index+m[0].length), head=t.slice(0,st);
    var season=/^\s*(?:a\/?w|f\/?w|秋冬|fall|winter)/i.test(tail) || /(?:a\/?w|f\/?w|秋冬|fall|winter)\s*$/i.test(head);
    if(y2>y1 && y2<=MAXY && !season){ got={k:'rng', v:e+'–'+b}; at=st; len=m[0].length-(st-m.index) }
  }
  // a decade: 1990s · late 1990’s · 1990年代後半
  if(!got && /0$/.test(e)){
    m=(new RegExp('(?:\\b(early|mid|late)[\\s-]*)?(?:^|[^0-9])?('+e+')'+S,'i')).exec(t);
    if(m){ got={k:'dec', v:e+'년대'+(m[1]?' '+QUAL[m[1].toLowerCase()]:'')}; at=m.index; len=m[0].length }
    else if((m=(new RegExp(e+'\\s*(?:年代|년대)\\s*(前半|初頭|中頃|後半|末)?')).exec(t))){
      got={k:'dec', v:e+'년대'+(m[1]?' '+QUAL[m[1]]:'')}; at=m.index; len=m[0].length }
  }
  // approximate: circa 2004 · c. 1997 · ca.1997 · early 2000
  if(!got){
    m=(new RegExp('(?:\\bcirca|\\bca\\.?|\\bc\\.|\\bearly|\\bmid|\\blate)[\\s-]*('+e+')(?![0-9])','i')).exec(t);
    if(m){ got={k:'about', v:e+'년 무렵'}; at=m.index; len=m[0].length }
  }
  if(!got) return null;
  // the same year written once more on its own is a year after all
  var rest=t.slice(0,at)+' '+t.slice(at+len);
  var bare=new RegExp('(?:^|[^0-9])'+e+'(?![0-9])(?!'+S+')(?!\\s*(?:年代|년대))(?!\\s*[-–—~〜～/]\\s*\\d)','i');
  return bare.test(rest)?null:got;
}
var CLAIMBASIS={dec:'연대 표기', rng:'기간 표기', about:'대략적 연도 표기',
  bought:'구입 연도 표기', y2k:'Y2K 표기', lang:'시기 표기', early:'시기 표기',
  arch:'아카이브 표기', multi:'여러 연도 표기'};
function yearOf(it){
  var e=it.__e!==undefined?it.__e:it.e;
  if(!e) return null;
  var m=/^(\d{4})$/.exec(e); if(m) return +m[1];
  var s=/^[A-Z]{2}(\d{2})$/.exec(e);
  if(s){var n=+s[1]; return n>=90?1900+n:2000+n}
  return null;
}
function priceBand(k){ for(var i=0;i<PRICE.length;i++) if(k>=PRICE[i][1]&&k<PRICE[i][2]) return PRICE[i][0];
  return PRICE[0][0] }
var own=Object.prototype.hasOwnProperty;
function keys(o){ var a=[],k; for(k in o) if(own.call(o,k)&&o[k]) a.push(k); return a }
function any(o){ for(var k in o) if(own.call(o,k)&&o[k]) return true; return false }
function motifLbl(k){ for(var i=0;i<MOTIF.length;i++) if(MOTIF[i][0]===k) return MOTIF[i][1]; return k }
var QT=[], QX=[];
function setQuery(q){
  F.q=q;
  QT=q?nrm(q).split(' ').filter(function(t){ return t && BRANDNOISE.indexOf(t)<0 }):[];
  QX=QT.map(alts);
}
function hit(it,t){
  var p=it.__t.indexOf(t);
  if(p>=0) return p===0?70:50;
  if(it.__mw.indexOf(t)>=0) return 30;
  if(it.__sec.indexOf(t)>=0) return 15;
  if(it.__meta.indexOf(t)>=0) return 8;
  return 0;
}
function score(it){
  if(!QT.length) return 0;
  var total=0;
  for(var i=0;i<QT.length;i++){
    // the word as typed, or the same thing in another of the three languages
    var best=hit(it,QT[i]), a=QX[i];
    for(var j=1;j<a.length;j++){ var tp=it.__t.indexOf(a[j]); if(tp>=0){ var h=tp===0?70:50; if(h>best) best=h } }
    if(!best) return 0;            // every token has to land somewhere
    total+=best;
  }
  // the whole phrase sitting in the title, in order, is the strongest signal
  if(QT.length>1 && it.__t.indexOf(QT.join(' '))>=0) total+=60;
  return total;
}
function matchedIn(it){
  var f={};
  for(var i=0;i<QT.length;i++){
    var best=hit(it,QT[i]), a=QX[i];
    for(var j=1;j<a.length;j++) if(it.__t.indexOf(a[j])>=0 && best<50) best=50;
    if(best>=50) f['상품명']=1;
    else if(best===30) f['기법·모델']=1;
    else if(best===15) f['분류']=1;
    else if(best===8) f['연도·판매처·사이즈·번호']=1;
  }
  return Object.keys(f);
}
var SEEK=[
 ['일본','야후옥션','ja',function(q){return 'https://auctions.yahoo.co.jp/search/search?p='+encodeURIComponent(q)}],
 ['일본','야후옥션','ja',function(q){return 'https://auctions.yahoo.co.jp/closedsearch/closedsearch?p='+encodeURIComponent(q)},'낙찰가'],
 ['일본','메루카리','ja',function(q){return 'https://jp.mercari.com/search?keyword='+encodeURIComponent(q)}],
 ['일본','라쿠마','ja',function(q){return 'https://fril.jp/s?query='+encodeURIComponent(q)}],
 ['일본','2nd STREET','en',function(q){return 'https://www.2ndstreet.jp/search?keyword='+encodeURIComponent(q)}],
 ['일본','Buyee','ja',function(q){return 'https://buyee.jp/item/search/query/'+encodeURIComponent(q)+'?lang=ko'},'구매대행'],
 ['한국','후루츠패밀리','ko',function(q,bare){return bare?'https://fruitsfamily.com/brand/Carol%20Christian%20Poell':'https://fruitsfamily.com/search/'+encodeURIComponent(q)}],
 ['한국','번개장터','ko',function(q){return 'https://m.bunjang.co.kr/search/products?q='+encodeURIComponent(q)}],
 ['해외','Grailed','en',function(q,bare){return bare?'https://www.grailed.com/designers/carol-christian-poell':'https://www.grailed.com/shop?query='+encodeURIComponent(q)}],
 ['해외','eBay','en',function(q){return 'https://www.ebay.com/sch/i.html?_nkw='+encodeURIComponent(q)}],
 ['해외','eBay','en',function(q){return 'https://www.ebay.com/sch/i.html?_nkw='+encodeURIComponent(q)+'&LH_Sold=1&LH_Complete=1'},'판매 완료'],
 ['해외','Depop','en',function(q){return 'https://www.depop.com/search/?q='+encodeURIComponent(q)}],
 ['해외','Vinted','en',function(q){return 'https://www.vinted.fr/catalog?search_text='+encodeURIComponent(q)},'유럽'],
 ['해외','Vinted','en',function(q){return 'https://www.vinted.com/catalog?search_text='+encodeURIComponent(q)},'미국'],
 ['해외','Vestiaire','en',function(q){return 'https://www.vestiairecollective.com/search/?q='+encodeURIComponent(q)}]
];
var SEEKBRAND={en:'carol christian poell',ja:'carol christian poell',ko:'캐롤크리스찬포엘'};
var HANGUL=/[\uac00-\ud7a3]/, KANA=/[\u3040-\u30ff\u4e00-\u9fff]/;
function lexRow(pred){ for(var i=0;i<LEX.length;i++) if(pred(LEX[i])) return LEX[i]; return null }
function word(row,L){ return row && row[L] && row[L].length ? row[L][0] : null }
function seekParts(){
  var parts=[];
  for(var i=0;i<QT.length;i++){
    var rows=Object.prototype.hasOwnProperty.call(LEXW,QT[i])?LEXW[QT[i]]:null;
    parts.push(rows?{row:rows[0],typed:QT[i]}:{raw:QT[i]});
  }
  var mo=keys(F.motif); if(mo.length===1){ var r=lexRow(function(x){return x.m===mo[0]}); if(r) parts.push({row:r}) }
  var ca=keys(F.cat); if(ca.length===1){ var rc=lexRow(function(x){return x.c===ca[0]}); if(rc) parts.push({row:rc}) }
  var ys=keys(F.y).filter(function(y){return y!=='none'}); if(ys.length===1) parts.push({raw:ys[0]});
  return parts;
}
function seekQuery(parts,L){
  var w=[SEEKBRAND[L]];
  parts.forEach(function(p){
    // the typed word itself when it belongs to this language (suit stays suit,
    // it does not become blazer); the row's first word only to translate
    var inL = p.typed && p.row[L] && p.row[L].some(function(w){ return nrm(w)===p.typed });
    var t = inL ? p.typed : p.row ? word(p.row,L) : p.raw;
    if(!t) return;
    // a word in one script sent to a platform that reads another finds nothing
    if(!p.row){ if(HANGUL.test(t) && L!=='ko') return; if(KANA.test(t) && L!=='ja') return; }
    if(w.indexOf(t)<0) w.push(t);
  });
  return w.join(' ');
}
function flagsHtml(it){
  var h='';
  // A without a value: the seller wrote the season (a shop's tag, a form the
  // English reader certified but did not copy out) — it is not 연도 미확인
  if(it.__e) h+='<span>'+esc(it.__e)+'</span>';
  else if(it.__yc) h+='<span class="d">'+esc(it.__yc.k==='arch'?'아카이브 표기':it.__yc.v)+'</span>';
  else if(it.c==='A') h+='<span>연도 표기</span>';
  else if(it.c==='B') h+='<span class="d">시기 표기</span>';
  else h+='<span class="s">연도 미확인</span>';
  if(it.so) h+='<span class="d">'+esc(it.sk||'판매 완료')+'</span>';
  if(it.n && !ALLNEW) h+='<span>신규</span>';
  if(it.w && it.w>it.k) h+='<span class="d">가격 내림</span>';
  return h;
}
function priceHtml(it,big){
  var alt=(it.u&&it.p>0)?'<span class="alt">'+(SYM[it.u]||'')+Number(it.p).toLocaleString('en-US')+'</span>':'';
  var was=(it.w&&it.w>it.k)?'<span class="was">₩'+won(it.w)+'</span>':'';
  return '<div class="'+(big?'big':'p')+'">₩'+won(it.k)+(alt?' '+alt:'')+(was?' '+was:'')+'</div>';
}
function thumb(u,w){
  if(!u) return u;
  try{
    if(u.indexOf('media-assets.grailed.com')>=0) return u+(u.indexOf('?')<0?'?':'&')+'w='+w;
    if(u.indexOf('cdn.shopify.com')>=0)          return u+(u.indexOf('?')<0?'?':'&')+'width='+w;
    if(u.indexOf('i.ebayimg.com')>=0)            return u.replace(/\/s-l\d+\.(jpg|png|webp)/i,
      '/s-l'+(w<=160?225:w<=400?400:w<=800?500:1600)+'.$1');
    if(u.indexOf('images.vestiairecollective.com')>=0) return u.replace(/\bw=\d+/, 'w='+w);
    // Mercari's list thumbnail is 240 px; the same photo at full size lives under /item/detail/orig/photos/
    if(u.indexOf('static.mercdn.net/thumb/item/')>=0 && w>=600) return u.replace(/\/thumb\/item\/webp\/(m\d+_\d+)\.jpg/, '/item/detail/orig/photos/$1.jpg');
    // Rakuma keeps a medium (m) and a large (l) copy of every photo; the large one only for the detail view
    if(u.indexOf('img.fril.jp/img/')>=0 && w>=1000) return u.replace(/\/m\/(\d+\.jpg)/, '/l/$1');
  }catch(e){}
  return u;
}
function photosOf(it){
  var a=[];
  if(it.i) a.push(it.i);
  if(Array.isArray(it.im)) it.im.forEach(function(u){
    if(typeof u==='string' && /^https?:\/\//.test(u) && a.indexOf(u)<0) a.push(u) });
  return a.slice(0,12);
}
function histHtml(it){
  if(!it.h||it.h.length<2) return '';
  var cur=it.u||'', sym=cur&&cur!=='KRW'?(SYM[cur]||cur+' '):'';
  var nat=function(pt){ return pt.length>2 && pt[2]>0 ? pt[2] : null };
  var haveNat=it.h.every(function(pt){ return nat(pt)!=null });
  // For a listing priced in another currency, the won figure alone cannot say
  // whether the seller moved: the rate moves it too. Points recorded before
  // the seller's price was kept carry only won, and for those we show the
  // dates and what we converted, and say nothing about direction.
  var krwIsSeller = !cur || cur==='KRW';
  var canJudge = haveNat || krwIsSeller;
  var rows=it.h.map(function(pt,i){
    var d=pt[0], v=pt[1], p=nat(pt);
    var pv=i>0?it.h[i-1]:null;
    // compare like with like: seller's number if both ends have one
    var a = haveNat&&pv ? nat(pv) : (pv?pv[1]:null);
    var b = haveNat ? p : v;
    var delta='';
    if(canJudge && a!=null && b!==a) delta='<em class="'+(b<a?'dn':'up')+'">'+
      (b<a?'−':'+')+(haveNat?sym+Number(Math.abs(b-a)).toLocaleString('en-US'):won(Math.abs(b-a)))+'</em>';
    var alt = (haveNat && sym) ? '<span class="alt">'+sym+Number(p).toLocaleString('en-US')+'</span>' : '';
    return '<div><span>'+esc(d)+'</span><b>₩'+won(v)+alt+delta+'</b></div>';
  }).join('');
  var f0=it.h[0], l0=it.h[it.h.length-1];
  var first = haveNat ? nat(f0) : f0[1], last = haveNat ? nat(l0) : l0[1];
  var net='';
  if(!canJudge){
    net='<div class="net">원화 환산가만 기록됨</div>';
  } else if(first!==last && first>0){
    var amt = haveNat ? sym+Number(Math.abs(last-first)).toLocaleString('en-US') : won(Math.abs(last-first));
    net='<div class="net">'+(last<first?'내림 ':'오름 ')+amt+' · '+
      (Math.abs(last-first)/first*100).toFixed(1).replace(/\.0$/,'')+'%</div>';
  }
  return '<div class="hist"><span class="lbl">가격 변동</span>'+rows+net+'</div>';
}
function keyOf(it){
  if(it.__k) return it.__k;
  var h=0x811c9dc5, u=it.l||'';
  for(var i=0;i<u.length;i++){ h^=u.charCodeAt(i); h=Math.imul(h,0x01000193)>>>0 }
  return (it.__k=h.toString(36));
}
var CATSLUG={'아우터':'outer','테일러링':'tailoring','셔츠':'shirts','상의':'tops','팬츠':'pants',
  '데님':'denim','신발':'shoes','가방·소품':'bags','주얼리':'jewelry','기타':'other'};
var PRICESLUG={'~50만':'under-500k','50–150만':'500k-1.5m','150–300만':'1.5m-3m','300만~':'over-3m'};
var CERTSLUG={A:'confirmed',B:'archive',C:'unknown'};
function packYears(ks){
  var ns=ks.filter(function(k){return /^\d{4}$/.test(k)}).map(Number).sort(function(a,b){return a-b});
  var rest=ks.filter(function(k){return !/^\d{4}$/.test(k)});
  var out=[],i=0;
  while(i<ns.length){
    var j=i; while(j+1<ns.length && ns[j+1]===ns[j]+1) j++;
    out.push(j>i?ns[i]+'-'+ns[j]:String(ns[i])); i=j+1;
  }
  return out.concat(rest);
}
function unpackYears(parts){
  var out=[];
  parts.forEach(function(p){
    var m=/^(\d{4})-(\d{4})$/.exec(p);
    if(m){ var a=+m[1],b=+m[2]; if(b<a){var t=a;a=b;b=t}
      for(var y=Math.max(a,YMIN);y<=Math.min(b,YMAX);y++) out.push(String(y)); }
    else out.push(p);
  });
  return out;
}
/* ---- end of copy ---- */
function prep(it){
  var ycE=yearClaim(it);
  it.__yc=ycE || (it.q ? {k:it.qk||'arch', v:it.q} : null);
  it.__e=ycE?null:(it.e||null);
  it.__c=ycE?'B':(it.__e?'A':it.c);
  it.__y=yearOf(it);
  it.__yk=it.__y?String(it.__y):'none';
  it.__m=[]; var mw='';
  var tk=it.t||''; try{ tk=tk.normalize('NFKC') }catch(e){}
  for(var j=0;j<MOTIF.length;j++) if(MOTIF[j][2].test(tk)){ it.__m.push(MOTIF[j][0]); mw+=' '+MOTIF[j][0]+' '+MOTIF[j][1] }
  it.__mk=marksOf(tk,it);
  it.__z=sizeToks(it);
  it.__t=nrm(it.t);
  it.__mw=nrm(mw);
  it.__sec=nrm(it.s);
  it.__meta=nrm((it.e||'')+' '+(it.r||'')+' '+(it.z||'')+' '+codeForms(it.mc));
  it.__s=it.__t+' '+it.__mw+' '+it.__sec+' '+it.__meta;
}
return {tag:'ccp', won:won, SYM:SYM, esc:esc, MOTIF:MOTIF, LEX:LEX, BRANDNOISE:BRANDNOISE, codeForms:codeForms, codeNum:codeNum, nrm:nrm, LEXW:LEXW, alts:alts, PRICE:PRICE, CERT:CERT, FLAGLBL:FLAGLBL, CATORDER:CATORDER, GRP:GRP, MARK:MARK, MARKLBL:MARKLBL, marksOf:marksOf, SZGRP:SZGRP, SZNAME:SZNAME, LETTERS:LETTERS, oneSize:oneSize, sizeToks:sizeToks, curOf:curOf, dnum:dnum, daysBetween:daysBetween, seenDays:seenDays, seenText:seenText, md:md, AEQ:AEQ, aucLeft:aucLeft, aucText:aucText, endText:endText, buyeeUrl:buyeeUrl, compsHtml:compsHtml, DOMESTIC:DOMESTIC, usdOf:usdOf, dutyHtml:dutyHtml, QUAL:QUAL, yearClaim:yearClaim, CLAIMBASIS:CLAIMBASIS, yearOf:yearOf, priceBand:priceBand, keys:keys, any:any, motifLbl:motifLbl, setQuery:setQuery, hit:hit, score:score, matchedIn:matchedIn, SEEK:SEEK, SEEKBRAND:SEEKBRAND, HANGUL:HANGUL, lexRow:lexRow, word:word, seekParts:seekParts, seekQuery:seekQuery, thumb:thumb, photosOf:photosOf, histHtml:histHtml, keyOf:keyOf, CATSLUG:CATSLUG, PRICESLUG:PRICESLUG, CERTSLUG:CERTSLUG, packYears:packYears, unpackYears:unpackYears, flagsHtml:flagsHtml, priceHtml:priceHtml,
  prep:prep,
  setData:function(d){ D=d; TODAY=d.today||null; var c=d.counts||{}; ALLNEW=!!(c.items && c.fresh>=c.items) },
  setF:function(f){ F=f },
  setSince:function(s){ SINCE=s },
  getQT:function(){ return QT.slice() },
  hasCodes:true};
})();
